name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  formula:
    name: Formula syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check formula syntax
        run: ruby -c Formula/*.rb
